name: Checkmarx One Scan

# use only job-level permissions
permissions: {}

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ 'main' ]
  workflow_dispatch: {}   # so you can still run it manually
  schedule:
    - cron: "0 0 * * *"   # run daily at midnight UTC
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
      security-events: write
      actions: read              # to query workflows/runs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      # Once public, can simplify to: uses: 
      - name: Checkmarx Full Scan
        uses: midnightntwrk/upload-sarif-github-action/checkmarx-scan-public@53cdf3148dbbd85518ecc5e8f1ec485852c99c36
        with:
          cx-client-id: ${{ secrets.CX_CLIENT_ID }}
          cx-client-secret: ${{ secrets.CX_CLIENT_SECRET_EU }}
          cx-tenant: ${{ secrets.CX_TENANT }}
          scs-repo-token: ${{ secrets.MIDNIGHTCI_REPO }}
          upload-to-github: 'true'
