name: VSC Plugin Integration Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start xvfb
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Run integration tests
        env:
          DISPLAY: ':99.0'
          ELECTRON_DISABLE_GPU: '1'
          ELECTRON_ENABLE_LOGGING: '1'
          DBUS_SESSION_BUS_ADDRESS: '/dev/null'
          NODE_OPTIONS: '--no-sandbox'
        run: |
          cd ./editor-support/vsc/compact
          yarn install --frozen-lockfile
          yarn compile
          yarn test-it
